sudo: true
language: cpp

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
  - eval "${MATRIX_EVAL}"
         
compiler:
  - g++
os:
  - linux
    
install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then  sudo apt-get install -qq cmake; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then  sudo apt-get install -qq git; fi
  
before_script:
  - cd 3rd
  - git clone https://github.com/google/glog.git
  - cd glog
  - git checkout v0.3.4
  - ./configure --prefix=/home/travis/build/pojol/gsf/lib/glog
  - make && make install

script:
  - cd /home/travis/build/pojol/gsf
  - cmake --version
  - cmake .
  - make