sudo: true
language: cpp

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

before_install:
  - eval "${MATRIX_EVAL}"

compiler:
  - g++
os:
  - linux
    
install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then  sudo apt-get install -qq cmake; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then  sudo apt-get install -qq git; fi
  
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then  sudo apt-get install -qq unzip; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then  sudo apt-get install -qq libtool; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then  sudo apt-get install -qq autoconf; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then  sudo apt-get install -qq automake; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then  sudo apt-get install -qq curl; fi

before_script:
  - python 3rd/update_3rd.py

script:
  - cmake --version
  - cmake .
  - make